name: StyleCI
on:
    pull_request:
        branches:
            - release
jobs:
    analyze_code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.1"

            - name: Install Composer
              run: |
                  curl -sS https://getcomposer.org/installer -o composer-setup.php
                  php composer-setup.php --install-dir=/usr/local/bin --filename=composer
              working-directory: /home/runner/work/otaku-tool/otaku-tool/framework

            - name: Install StyleCI CLI
              run: |
                  composer require styleci/cli:^1.5 --dev
              working-directory: /home/runner/work/otaku-tool/otaku-tool/framework

            - name: Analyze Code with StyleCI
              run: /home/runner/work/otaku-tool/otaku-tool/framework/vendor/bin/styleci analyze --dry-run
              with:
                  styleci_api_key: ${{ secrets.STYLECI_API_KEY }} # required
