name: StyleCI
on:
    pull_request:
        branches:
            - release
jobs:
    analyze_code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.1"

            - name: Install Composer
              run: |
                  curl -sS https://getcomposer.org/installer -o composer-setup.php
                  php composer-setup.php --install-dir=/usr/local/bin --filename=composer

            - name: Install StyleCI CLI
              run: |
                  curl -sS https://github.styleci.io/projects/cli-installer -o installer.php
                  php installer.php install
              env:
                  STYLECI_API_KEY: ${{ secrets.STYLECI_API_KEY }}

            - name: Analyze Code with StyleCI
              run: styleci analyze --no-interaction
              working-directory: /home/runner/work/otaku-tool/otaku-tool
